export const FarmItems = [
  {
    title: "USDC.e-WAVAX Avolidly Variable LP",
    url: "/farms/0",
    cName: "farm-links",
    symbol1: "USDC.e",
    symbol2: "WAVAX",
    boost: "1",
  },
  {
    title: "WAVAX-USDT.e Avolidly Variable LP",
    url: "/farms/1",
    cName: "farm-links",
    symbol1:"WAVAX",
    symbol2:"USDT.e",
    boost: "1",
  },
  {
    title: "WETH.e-WAVAX Avolidly Variable LP",
    url: "/farms/2",
    cName: "farm-links",
    symbol1: "WETH.e",
    symbol2: "WAVAX",
    boost: "1",
  },
  {
    title: "sAVAX-WAVAX Avolidly Variable LP",
    url: "/farms/3",
    cName: "farm-links",
    symbol1: "sAVAX",
    symbol2: "WAVAX",
    boost: "1",
  },
  {
    title: "JOE-WAVAX Avolidly Variable LP",
    url: "/farms/4",
    cName: "farm-links",
    symbol1: "JOE",
    symbol2: "WAVAX",
    boost: "1",
  },
  {
    title: "USDC.e-USDC Avolidly Stable LP",
    url: "/farms/5",
    cName: "farm-links",
    symbol1: "USDC.e",
    symbol2: "USDC",
    boost: "1",
  },
  {
    title: "WBTC.e-WAVAX Avolidly Variable LP",
    url: "/farms/6",
    cName: "farm-links",
    symbol1: "WBTC.e",
    symbol2: "WAVAX",
    boost: "1",
  },
  {
    title: "AVLD-WAVAX Trader Joe LP",
    url: "/farms/7",
    cName: "farm-links",
    symbol1: "AVLD",
    symbol2: "WAVAX",
    boost: "1",
  },
];
